# Değişken Dönüşümleri

In [1]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## 0-1 Dönüşümü

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
lbe = LabelEncoder()

In [4]:
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [6]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
df["yeni_sex"] = lbe.fit_transform(df["sex"])

In [8]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

## 1 ve Diğerleri(0) Dönüşümü

In [9]:
#İkiden fazla sınıf olunca seçmiş olduğumuz birine 1 diğerlerine 0 diyecek olursak

In [15]:
import numpy as np
df["yeni_day"] = np.where(df["day"].str.contains("sun"), 1, 0)
#sun olanlara 1 digerlerine 0 ver (contains sorgulama sun var mı varsa 1)

In [14]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1         0
2         21.01  3.50    Male     No   Sun  Dinner     3         1         0
3         23.68  3.31    Male     No   Sun  Dinner     2         1         0
4         24.59  3.61  Female     No   Sun  Dinner     4         0         0
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

## Çok Sınıflı Dönüşüm

In [9]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [17]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [19]:
# Sınıflar eşitken değer sırası gibi oluyor çok sınıflı dönüşümler problemlere sebep olabilir

# One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [20]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  yeni_day
0       16.99  1.01  Female     No  Sun  Dinner     2         0         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1         0
2       21.01  3.50    Male     No  Sun  Dinner     3         1         0
3       23.68  3.31    Male     No  Sun  Dinner     2         1         0
4       24.59  3.61  Female     No  Sun  Dinner     4         0         0

In [21]:
import pandas as pd

In [22]:
df_one_hot = pd.get_dummies(df, columns = ["sex"], prefix = ["sex"])

In [23]:
df_one_hot.head()

total_bill   tip smoker  day    time  size  yeni_sex  yeni_day  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2         0         0         0   
1       10.34  1.66     No  Sun  Dinner     3         1         0         1   
2       21.01  3.50     No  Sun  Dinner     3         1         0         1   
3       23.68  3.31     No  Sun  Dinner     2         1         0         1   
4       24.59  3.61     No  Sun  Dinner     4         0         0         0   

   sex_Female  
0           1  
1           0  
2           0  
3           0  
4           1

In [27]:
pd.get_dummies(df, columns = ["day"], prefix = ["day"])

total_bill   tip     sex smoker    time  size  yeni_sex  yeni_day  \
0         16.99  1.01  Female     No  Dinner     2         0         0   
1         10.34  1.66    Male     No  Dinner     3         1         0   
2         21.01  3.50    Male     No  Dinner     3         1         0   
3         23.68  3.31    Male     No  Dinner     2         1         0   
4         24.59  3.61  Female     No  Dinner     4         0         0   
..          ...   ...     ...    ...     ...   ...       ...       ...   
239       29.03  5.92    Male     No  Dinner     3         1         0   
240       27.18  2.00  Female    Yes  Dinner     2         0         0   
241       22.67  2.00    Male    Yes  Dinner     2         1         0   
242       17.82  1.75    Male     No  Dinner     2         1         0   
243       18.78  3.00  Female     No  Dinner     2         0         0   

     day_Thur  day_Fri  day_Sat  day_Sun  
0           0        0        0        1  
1           0        0        0        1  
2           0        0        0        1  
3           0        0        0        1  
4           0        0        0        1  
..        ...      ...      ...      ...  
239         0        0        1        0  
240         0        0        1        0  
241         0        0        1        0  
242         0        0        1        0  
243         1        0        0        0  

[244 rows x 12 columns]

# Sürekli Değişkeni Kategorik Değişkene Çevirme

In [2]:
import seaborn as sns
df2 = sns.load_dataset("tips")
df2.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
from sklearn import preprocessing

In [12]:
dff = df2.select_dtypes(include = ["float64", "int64"])

In [13]:
est = preprocessing.KBinsDiscretizer(n_bins = [3,2,2], encode = "ordinal", strategy = "quantile").fit(dff)

In [14]:
est.transform(dff)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [15]:
# Çok gerekmedikçe kullanımayan bir durumdur.

# Değişkeni İndexe İndexi Değişkene Çevirme

In [16]:
df2.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
df2["yeni_degisken"] = df2.index

In [19]:
df2.head()

total_bill   tip     sex smoker  day    time  size  yeni_degisken
0       16.99  1.01  Female     No  Sun  Dinner     2              0
1       10.34  1.66    Male     No  Sun  Dinner     3              1
2       21.01  3.50    Male     No  Sun  Dinner     3              2
3       23.68  3.31    Male     No  Sun  Dinner     2              3
4       24.59  3.61  Female     No  Sun  Dinner     4              4

In [20]:
df2["yeni_degisken"] = df2["yeni_degisken"] + 10

In [22]:
df2.head()

total_bill   tip     sex smoker  day    time  size  yeni_degisken
0       16.99  1.01  Female     No  Sun  Dinner     2             10
1       10.34  1.66    Male     No  Sun  Dinner     3             11
2       21.01  3.50    Male     No  Sun  Dinner     3             12
3       23.68  3.31    Male     No  Sun  Dinner     2             13
4       24.59  3.61  Female     No  Sun  Dinner     4             14

In [24]:
df2.index = df2["yeni_degisken"]

In [26]:
df2.index

Int64Index([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,
            ...
            244, 245, 246, 247, 248, 249, 250, 251, 252, 253],
           dtype='int64', name='yeni_degisken', length=244)